from __future__ import annotations

import re
import secrets
from datetime import UTC, datetime, timedelta

# One id rule for memories and projects: 10 random lowercase Crockford base32
# characters (50 bits), generated by the system and never proposed by a
# caller. Short on purpose: every id is injected into agent context in the
# index and copied back into tool calls. The alphabet leaves out i, l, o and
# u so an id survives being read and retyped. Uniqueness is the stores' job:
# they refuse an id that is taken.
ID_ALPHABET = "0123456789abcdefghjkmnpqrstvwxyz"
ID_LENGTH = 10
ID_RE = re.compile(r"[0-9a-hjkmnp-tv-z]{10}")


def new_id() -> str:
    return "".join(secrets.choice(ID_ALPHABET) for _ in range(ID_LENGTH))


# stored fields and path-derived text are hand-editable, and index lines are
# injected into agent context automatically, so no field may smuggle a newline
# or an embedded instruction into another line: control characters and Unicode
# line separators collapse to spaces before a value is placed on a line
_LINE_UNSAFE_RE = re.compile(r"[\x00-\x1f\x7f-\x9f\u2028\u2029]")


def single_line(value: str) -> str:
    return " ".join(_LINE_UNSAFE_RE.sub(" ", value).split())


def now() -> str:
    # microseconds, not seconds: `updated` is the recency sort key, and a
    # same-second update must still advance it
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%S.%fZ")


def now_strictly_after(previous: str) -> str:
    """`now()`, forced past `previous` when the clock has not moved on.

    Resolution alone does not guarantee an advance: the clock's own tick can
    be coarser than two consecutive writes, and it can step backwards. Since
    `updated` is the recency sort key, a rewrite that landed on -- or before
    -- the value it replaces would let the older body sort as the newer one.
    A `previous` outside the canonical form carries no comparable instant, so
    there the plain clock reading is all there is; diagnostics reports that
    value separately.
    """
    stamp = now()
    try:
        earliest = (datetime.strptime(previous, "%Y-%m-%dT%H:%M:%S.%fZ").replace(tzinfo=UTC)
                    + timedelta(microseconds=1)).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
    except (ValueError, OverflowError):
        return stamp
    # both are the same fixed-width form, so lexicographic order is chronological
    return max(stamp, earliest)
