from __future__ import annotations

import re
import secrets

# One id rule for memories and projects: 10 random lowercase Crockford base32
# characters (50 bits), generated by the system and never proposed by a
# caller. Short on purpose: every id is injected into agent context in the
# index and copied back into tool calls. The alphabet leaves out i, l, o and
# u so an id survives being read and retyped. Uniqueness is the stores' job:
# they refuse an id that is taken, and the facade draws again.
ID_ALPHABET = "0123456789abcdefghjkmnpqrstvwxyz"
ID_LENGTH = 10
ID_RE = re.compile(r"[0-9a-hjkmnp-tv-z]{10}")


def new_id() -> str:
    return "".join(secrets.choice(ID_ALPHABET) for _ in range(ID_LENGTH))


# stored fields and path-derived text are hand-editable, and index lines are
# injected into agent context automatically, so no field may smuggle a newline
# or an embedded instruction into another line: control characters and Unicode
# line separators collapse to spaces before a value is placed on a line
_LINE_UNSAFE_RE = re.compile(r"[\x00-\x1f\x7f-\x9f\u2028\u2029]")


def single_line(value: str) -> str:
    return " ".join(_LINE_UNSAFE_RE.sub(" ", value).split())
