from __future__ import annotations

import re
import secrets
from datetime import UTC, datetime, timedelta

# One id rule for memories and projects: 10 random lowercase Crockford base32
# characters (50 bits), generated by the system and never proposed by a
# caller. Short on purpose: every id is injected into agent context in the
# index and copied back into tool calls. The alphabet leaves out i, l, o and
# u so an id survives being read and retyped. Uniqueness is the stores' job:
# they refuse an id that is taken.
ID_ALPHABET = "0123456789abcdefghjkmnpqrstvwxyz"
ID_LENGTH = 10
ID_RE = re.compile(r"[0-9a-hjkmnp-tv-z]{10}")


# a harness name is persisted verbatim into stored rows, so without a shape
# check it is a policy-free channel for secrets or megabytes of text. The shape
# caps size and charset; the content policy then rejects the values that still
# look like credentials. Neither check echoes the rejected value.
HARNESS_RE = re.compile(r"[A-Za-z0-9._-]{1,64}")


def new_id() -> str:
    return "".join(secrets.choice(ID_ALPHABET) for _ in range(ID_LENGTH))


# stored fields and path-derived text are hand-editable, and index lines are
# injected into agent context automatically, so no field may smuggle a newline
# or an embedded instruction into another line: control characters and Unicode
# line separators collapse to spaces before a value is placed on a line
_LINE_UNSAFE_RE = re.compile(r"[\x00-\x1f\x7f-\x9f\u2028\u2029]")


def single_line(value: str) -> str:
    return " ".join(_LINE_UNSAFE_RE.sub(" ", value).split())


# the exact shape `now()` produces: strftime's %f always pads to six digits,
# so this is a fixed-width form, and two of them compare lexicographically in
# chronological order (see now_strictly_after). [0-9], not \d: \d matches any
# Unicode decimal digit (full-width, Arabic-indic, ...), not just ASCII.
_TIMESTAMP_SHAPE_RE = re.compile(
    r"[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{6}Z")


def is_timestamp(value: object) -> bool:
    """Whether `value` is exactly the fixed-width UTC form `now()` produces.

    The shape alone is not enough: it accepts a calendar `strptime` would
    reject (month 99, February 30), and `strptime` alone is not enough either
    -- CPython's own %d/%m/%Y parsing uses \\d too, so it accepts the same
    non-ASCII digits the shape check exists to keep out. Both must pass.
    """
    if not (isinstance(value, str) and _TIMESTAMP_SHAPE_RE.fullmatch(value)):
        return False
    try:
        datetime.strptime(value, "%Y-%m-%dT%H:%M:%S.%fZ").replace(tzinfo=UTC)
    except ValueError:
        return False
    return True


def now() -> str:
    # microseconds, not seconds: `updated` is the recency sort key, and a
    # same-second update must still advance it
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%S.%fZ")


def now_strictly_after(previous: str) -> str:
    """`now()`, forced past `previous` when the clock has not moved on.

    Resolution alone does not guarantee an advance: the clock's own tick can
    be coarser than two consecutive writes, and it can step backwards. Since
    `updated` is the recency sort key, a rewrite that landed on -- or before
    -- the value it replaces would let the older body sort as the newer one.
    A `previous` outside the canonical form carries no comparable instant, so
    there the plain clock reading is all there is; diagnostics reports that
    value separately.
    """
    stamp = now()
    try:
        earliest = (datetime.strptime(previous, "%Y-%m-%dT%H:%M:%S.%fZ").replace(tzinfo=UTC)
                    + timedelta(microseconds=1)).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
    except (ValueError, OverflowError):
        return stamp
    # both are the same fixed-width form, so lexicographic order is chronological
    return max(stamp, earliest)


_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
# strftime does not zero-pad a year below 1000 on every platform, so the two
# edges are spelled out rather than formatted
_EARLIEST = "0001-01-01T00:00:00.000000Z"
_LATEST = "9999-12-31T23:59:59.999999Z"


def timestamp_shift(value: str, *, days: float = 0, minutes: float = 0) -> str:
    """`value` moved by `days` and `minutes` (negative: earlier), in the same fixed-width form.

    ValueError for a value that is not a timestamp. A result outside
    datetime's range clamps to its edge: a TTL cutoff before every stored
    instant, or a review date after all of them, is what such an offset means.
    """
    if not is_timestamp(value):
        raise ValueError("not a timestamp")
    moment = datetime.strptime(value, _FORMAT).replace(tzinfo=UTC)
    try:
        moved = moment + timedelta(days=days, minutes=minutes)
    except OverflowError:
        return _EARLIEST if days * 1440 + minutes < 0 else _LATEST
    if moved.year < 1000:
        return _EARLIEST
    return moved.strftime(_FORMAT)
